services:
   

    web:
      image: deakin1992/covidtrackingrecord:test
      restart: always
      ports:

        - "4040:4040"
    database:
        image: mongo
        
    watchtower:
            image: v2tec/watchtower
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
            command: --interval 30000